



class.sources = net/tcpsend.c \
net/tcpserver.c \
net/udpsend.c \
midifile/midifile.c \
cmos/cd4000.c \
cmos/cd4001.c \
cmos/cd4002.c \
cmos/cd4008.c \
cmos/cd4011.c \
cmos/cd4012.c \
cmos/cd4013.c \
cmos/cd4014.c \
cmos/cd4015.c \
cmos/cd4017.c \
cmos/cd4023.c \
cmos/cd4024.c \
cmos/cd4025.c \
cmos/cd4027.c \
cmos/cd4070.c \
cmos/cd4071.c \
cmos/cd4072.c \
cmos/cd4073.c \
cmos/cd4075.c \
cmos/cd4076.c \
cmos/cd4081.c \
cmos/cd4082.c \
cmos/cd4094.c \
cmos/cd4516.c \
cmos/cd40193.c \
op~/op~.c \
rc~/rc~.c \
rcosc~/rcosc~.c \
rojo~/rojo~.c \
tabfind/tabfind.c \
which/which.c \
flist2tab/flist2tab.c \
net/httpreceive.c \
net/httpreq.c \
life2x/life2x.c \
slipenc/slipenc.c \
sqosc~/sqosc~.c \
tab2flist/tab2flist.c \
net/tcpreceive.c \
net/udpreceive.c \
net/udpreceive~.c \
net/udpsend~.c \
osc/packOSC.c \
osc/pipelist.c \
osc/routeOSC.c \
osc/unpackOSC.c \
xbee/packxbee.c \
slipdec/slipdec.c \
xbee/unpackxbee.c \
runningmean/runningmean.c \
str/str.c \
binfile/binfile.c \
net/tcpclient.c \


ldlibs = -liphlpapi -lws2_32 -lwsock32 -lkernel32 -luser32 -lgdi32
          




include pd-lib-builder/Makefile.pdlibbuilder
